[package]
name = "denv"
version = "0.1.0"
description = "Dotenv (.env) loader written in rust"
authors = ["numtostr <vikasraj1911@gmail.com>"]
edition = "2018"
homepage = "https://github.com/numToStr/denv/"
repository = "https://github.com/numToStr/denv/"
license-file = "LICENSE"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
